language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
    - pecl install riak
    - composer install --dev
    - pyrus install pear/PHP_CodeSniffer
    - phpenv rehash

script:
    - phpunit
    - phpcs -np --extensions=php --ignore=vendor/*,Tests/* --standard=PSR2 .